services:
  db:
    image: postgres:16
    container_name: employee_db_lab
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
